version: '3'

services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: example-db
    ports:
      - "5433:5432"
    volumes:
      - my-db:/var/lib/postgresql/data
    networks:
      - demo_net

  user-microservice:
    build:
      context: ./tema1_repo/ds2025_spring_example/demo
      dockerfile: Dockerfile
    container_name: user-microservice
    ports:
      - "8081:8080"
    environment:
      - DB_IP=db
      - DB_PORT=5432
      - DB_DBNAME=userdb
      - DB_USER=postgres
      - DB_PASSWORD=root
    networks:
      - demo_net
    depends_on:
      - db

  device-microservice:
    build:
      context: ./device_microservice/device-service
      dockerfile: Dockerfile
    container_name: device-microservice
    ports:
      - "8082:8081"
    networks:
      - demo_net
    depends_on:
      - db

volumes:
  my-db:

networks:
  demo_net:
